docs: getting started - overview 작성
keti-openfx/openfx pull request #23
Opened 2020-08-31 05:48 UTC by imxsuu

# Pull Request

keti-openfx/openfx 레파지토리에 기여해주셔서 감사드립니다.

해당 PR을 제출하기 전에 아래 사항이 완료되었는지 확인 부탁드립니다:

- [ ] 작성한 코드가 어떤 에러나 경고없이 빌드가 되었나요?
- [ ] 충분한 테스트를 수행하셨나요?

## 1. 해당 PR은 어떤 내용인가요?

getting started - overview 작성

## 2. PR과 관련된 이슈가 있나요?

2020-09-03 08:01 UTC, ssaru commented on docs/source/3_getting_started/1_overview/index.md
> +OpenFx에 함수를 만들기 위해서는 다음과 같은 일련의 과정을 거쳐야 한다.
```suggestion
OpenFx에 함수의 라이프 사이클은 아래와 같다.
```

2020-09-03 08:02 UTC, ssaru commented on docs/source/3_getting_started/1_overview/index.md
> +![picture1](C:\Users\sujin\workspace\openfx\docs\source\3_getting_started\1_overview\picture1.png)
그림이 안나옵니다...

2020-09-03 08:12 UTC, ssaru commented on docs/source/3_getting_started/1_overview/index.md
> +OpenFx는 마이크로 서비스 구조의 서버리스 프레임워크이며 CLI 명령어를 통해 함수가 생성된다. 함수는 도커 컨테이너 기반으로 운영되며 사용자는 비즈니스 로직만 작성하여 배포하면 된다.
CLI 약어를 풀어서 써주시면 더 좋을 것 같습니다.

2020-09-03 08:15 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.md
> +  >`--gateway; -g` : Gateway의 주소와 포트번호; 함수 호출 시 사용하는 Gateway의 주소이다. 설정하지 않으면 기본값인  `keti.asuscomm.com:31113`으로 설정되며  사용하고자 하는 IP주소의 도메인 설정이 되어있다면 URL로도 사용이 가능하다.
이부분 렌더가 안됩니다.

아래 사이트에서 md파일을 rst로 변경해주시거나, `>`는 사용하지 않는 방향으로 부탁드립니다.
https://cloudconvert.com/md-to-rst

2020-09-03 08:26 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.md
> +    >`runtime` : 함수의 런타임 종류; OpenFx에서 지원하는 런타임은 모두 가능하다.
지원하는 런타임 종류를 다른 꼭지로 빼서 별도로 명시하는 구조가 좋은 것 같습니다.
단순히 "OpenFx에서 지원하는 런타임"라는 표기는 좋지 않아보입니다.

2020-09-03 09:40 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.md
> +    >`<REGISTRY IP>:<PORT>` : 사용자의 Docker registy의 IP 주소와 PORT 번호
용어 통일 부탁드립니다.
도커 레지스트리 or Docker registry

2020-09-03 09:42 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.md
> +### Deploy function
"### Test Function", "### Deploy function" 대소문자 일관성을 유지 부탁드립니다.

2020-09-03 09:44 UTC, ssaru commented on docs/source/3_getting_started/1_overview/index.md
> +![picture1](C:\Users\sujin\workspace\openfx\docs\source\3_getting_started\1_overview\picture1.png)
절대 경로가 아니라, 상대경로로 해주세요.

2020-09-03 09:47 UTC, ssaru commented on docs/source/3_getting_started/4_invoke_internal_service/index.md
> +마이크로 서비스 구조의 서버리스 프레임워크인 OpenFx에서 함수는 독립적으로 배포가 가능하며 개별적으로 실행될 수 있는 하나의 서비스로 정의된다. OpenFx에 배포되어 있는 서비스 내부에서 다른 서비스를 호출할 수 있으며, 이를 통해 사용자는 서로 다른 서비스를 엮어 원하는 기능의 애플리케이션 서비스를 완성할 수 있다.
호흡이 너무 깁니다.

```suggestion
OpenFx의 함수는 독립적으로 배포가 가능하며 개별적으로 실행될 수 있는 하나의 서비스로 정의된다. OpenFx에 배포된 서비스는 내부에서 다른 서비스를 호출할 수 있으며, 이를 통해 사용자는 서로 다른 서비스를 엮어 원하는 기능의 애플리케이션 서비스를 완성할 수 있다.
```

2020-09-03 09:48 UTC, ssaru commented on docs/source/3_getting_started/4_invoke_internal_service/index.md
> +서비스 간 호출을 지원하는 런타임들에 대해서 서비스를 호출하기 위한 Handler 코드 작성방법에 대해 설명한다. 새 함수 템플릿 생성 시, Handler 예제 코드의 기본 설정은 사용자가 단일 서비스 호출에 대한 응답을 바로 받을 수 있는 코드로 설정되어 있다.
"서비스 간 호출을 지원하는 런타임들에 대해서" -> 서비스 간 호출을 지원하는 런타임 목록을 명시해주는게 좋을 것 같습니다.

2020-09-03 09:57 UTC, ssaru commented on docs/source/3_getting_started/4_invoke_internal_service/index.md
> +Handler 코드 작성 후에, [Deploy Functions](#Deploy Functions)부터 순차적으로 진행하면 다른 서비스를 호출하는 함수가 OpenFx에 배포된다. 사용자가 엮은 서비스의 시작점에 있는 서비스를 호출해야 정상적으로 호출된다.
링크가 제대로 연결되지 않았습니다.

2020-09-03 09:58 UTC, ssaru requested changes
@imxsuu 코멘트 완료했습니다.

2020-09-04 04:41 UTC, imxsuu commented on docs/source/3_getting_started/4_invoke_internal_service/index.md
> +Handler 코드 작성 후에, 다음 [링크](http://github.com/keti-openfx/openfx/docs/source/3_getting_started/2_deploying_functions/index.rst)의 #Build Function부터 순차적으로 진행하면 다른 서비스를 호출하는 함수가 OpenFx에 배포된다. 호출 시에는 사용자가
왜 not found라고 뜨는지 모르겠네요..

2020-09-04 07:33 UTC, ssaru commented on docs/source/3_getting_started/1_overview/index.md
> +OpenFx는 마이크로 서비스 구조의 서버리스 프레임워크이며 CLI(Command line interface) 명령어를 통해 함수가 생성된다. 함수는 도커 컨테이너 기반으로 운영되며 사용자는 비즈니스 로직만 작성하여 배포하면 된다.
이 부분 깔끔하네요.

2020-09-04 07:36 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +사용되는 CLI 명령어 사용법과 그 과정에 대해서 자세히 다룬다.
함수를 빌드, 배포, 호출하는 과정에서 CLI 명령어 사용법과 과정은 자연스럽게 나타나니 구도로 별도 표기하지 않아도 될 것 같습니다.

```suggestion
본 챕터에서는 OpenFx의 CLI(Command line interface) 명령어를 통해
사용자가 정의한 함수를 빌드, 배포, 호출되기까지의 과정을 다룬다.
```

2020-09-04 07:37 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +``$ openfx-cli function init <FUNCTION NAME> -r <RUNTIME> [-f <YAML FILE NAME>.yaml] [-g <호스트 OS IP>:31113>]   >>    Folder: <FUNCTION NAME> created   Fucntion handler created in folder: <FUNCTION NA
`make html`하고, `openfx/docs/_build/index.html`파일 열어서 확인했을 때, 이상이 없었나요?

제가 했을 때, 아래와 같이 텍스트가 레이아웃을 벗어납니다.
![렌더결과](https://user-images.githubusercontent.com/13328380/92212458-f3d84f00-eecc-11ea-9837-2c2c0b8f66c0.PNG)

2020-09-04 07:39 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +    영문 소문자로 작성해야 한다.
"생성하고자 하는 함수의 이름. (_첫문자는 반드시 영문 소문자로 작성한다._)" 이런 형태가 어떨런지요?

2020-09-04 07:40 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +    모두 가능하다.
```suggestion
    ``--runtime; -r`` : OpenFx가 지원하는 함수 런타임
```

2020-09-04 07:41 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +    -  Java
계층 구조가 이상합니다.
아래와 같은 구조가 더 좋지 않을까 싶습니다.

-  OpenFx는 아래와 같이 다양한 런타임을 지원한다.
    -  Golang
    -  Python 2.7 / 3.6
    -  Ruby
    -  CPP
    -  C#
    -  Node.js
    -  Java

2020-09-04 07:42 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +    ``config.yaml``\ 으로 생성된다.
``--config; -f`` : 함수 설정 파일의 이름(_설정하지 않으면 기본값인 `config.yaml` 으로 생성된다_).

2020-09-04 07:44 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +    영문 소문자로 작성해야 한다.
아니면, 괄호에 들어가는 내용은 Reference 란에 빼도 괜찮을 것 같습니다. 
Getting Started 내에서 함수를 배포하는 과정에서 구두로 설명하는 것 도 괜찮아보이구요.

2020-09-04 07:45 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +    도메인 설정이 되어있다면 URL로도 사용이 가능하다.
[위에서 언급했던 내용](https://github.com/keti-openfx/openfx/pull/23/files/32251adddfad93b9bd903bb6d12d0c5aa526b436#r483443738)과 동일합니다.

2020-09-04 07:46 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +​ └── handler.
여기는 여전히 깨집니다.

![파일디렉토리계층](https://user-images.githubusercontent.com/13328380/92213201-19b22380-eece-11ea-9a51-4f7b4a631102.PNG)

2020-09-04 07:47 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +
조금 내용을 고민해봤는데, Getting Started 안에 너무 많은 정보가 들어가는 것 같습니다.
자세한 내용은 Reference - Command line interface란을 따로 만들고, 거기에 내용을 옮기는게 좋을 것 같습니다.

2020-09-04 07:51 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +
일전에 알려드린 변환사이트가 h4 헤더를 변환하지 못하는 것 같습니다.
필요에 따라 [rst관련 블로그](https://fwani.tistory.com/3)내용을 참고해서 rst 파일 내부에서 헤더 타이틀을 수정 부탁드립니다.

![h4헤더](https://user-images.githubusercontent.com/13328380/92214057-d906da00-eece-11ea-879d-1886080b56a0.PNG)

2020-09-04 07:53 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +
[위에서 언급한 것 과 같이](https://github.com/keti-openfx/openfx/pull/23/files/32251adddfad93b9bd903bb6d12d0c5aa526b436#r483442797) 레이아웃을 벗어납니다.

2020-09-04 07:56 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +코드를 응용하여 함수의 실행 코드를 작성할 수 있다.
```suggestion
다음은 기본적으로 생성되는 런타임별 함수 템플릿이다. 템플릿 코드는 입력된 데이터를 그대로 반환해주는 echo 함수이다.

사용자는 다음의 예제코드를 응용하여 함수의 실행 코드를 작성할 수 있다.
```

2020-09-04 08:01 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +``$ openfx-cli function init <FUNCTION NAME> -r <RUNTIME> [-f <YAML FILE NAME>.yaml] [-g <호스트 OS IP>:31113>]   >>    Folder: <FUNCTION NAME> created   Fucntion handler created in folder: <FUNCTION NA
또한, 실제 사용자가 따라쳤을 때, 실행되는 예제여야합니다.
작성하신 위 가이드를 보면, 사용자는 이런 저런 실험을 해봐야합니다.

직접적으로 echo함수의 예제코드를 작성하는 방향으로 가이드하면서
실제 명령어를 제공해주는게 좋습니다.
예 >> `openfx-cli function init echo -r python`

2020-09-04 08:02 UTC, imxsuu commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +``$ openfx-cli function init <FUNCTION NAME> -r <RUNTIME> [-f <YAML FILE NAME>.yaml] [-g <호스트 OS IP>:31113>]   >>    Folder: <FUNCTION NAME> created   Fucntion handler created in folder: <FUNCTION NA
이게 파일을 변환하면서 개행이 다 깨지는 것 같아요..

2020-09-04 08:03 UTC, imxsuu commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +    -  Java
이것도 파일 변환하면서 깨진듯하네요..

2020-09-04 08:06 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +
[위에서 언급한 것 과 같이](https://github.com/keti-openfx/openfx/pull/23/files/32251adddfad93b9bd903bb6d12d0c5aa526b436#r483442797) 레이아웃을 벗어납니다.

2020-09-04 08:06 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +``$ openfx-cli function list [-g <호스트 OS IP>:31113>]    >>     Function            Image                         Maintainer    Invocations    Replicas    Status    Description    <FUNCTION NAME>
[위에서 언급한 것 과 같이](https://github.com/keti-openfx/openfx/pull/23/files/32251adddfad93b9bd903bb6d12d0c5aa526b436#r483442797) 레이아웃을 벗어납니다.

2020-09-04 08:06 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +``$ echo "Hello" | openfx-cli function call <FUNCTION NAME> [-g <호스트 OS IP>:31113>]    >>    Hello``
[위에서 언급한 것 과 같이](https://github.com/keti-openfx/openfx/pull/23/files/32251adddfad93b9bd903bb6d12d0c5aa526b436#r483442797) 레이아웃을 벗어납니다.

2020-09-04 08:06 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +``$ openfx-cli function info <FUNCTION NAME> [-g <호스트 OS IP>:31113>]    >>    name: <FUNCTION NAME>    image: <REGISTRY IP>:<PORT>/<FUNCTION NAME>    invocationcount: 4    replicas: 1    annotations:
[위에서 언급한 것 과 같이](https://github.com/keti-openfx/openfx/pull/23/files/32251adddfad93b9bd903bb6d12d0c5aa526b436#r483442797) 레이아웃을 벗어납니다.

2020-09-04 08:06 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +``$ openfx-cli function log <FUNCTION NAME> [-g <호스트 OS IP>:31113>]    >>    ---    Name: <FUNCTION NAME>    Log:     ...``
[위에서 언급한 것 과 같이](https://github.com/keti-openfx/openfx/pull/23/files/32251adddfad93b9bd903bb6d12d0c5aa526b436#r483442797) 레이아웃을 벗어납니다.

2020-09-04 08:07 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +\`\`\` $ echo "Hello" \| openfx-cli function run [-f .yaml] >> Running
렌더가 제대로 안됩니다.

![not_rendered](https://user-images.githubusercontent.com/13328380/92216294-140a0d00-eed1-11ea-9f8c-7ba80ebcd949.PNG)

2020-09-04 08:08 UTC, imxsuu commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +​ └── handler.
이것도 제가 계속 확인을 해봤는데.. 계속 깨지더라구요.. 아무래도 파일 변환한 이유가 `>` 때문이니.. 그걸 대체할 만한 다른 문법을 찾아서 다시 md파일로 작성할게요.. 파일변환에 따른 노동이 너무 증가하네요..

2020-09-04 08:11 UTC, ssaru commented on docs/source/3_getting_started/4_invoke_internal_service/index.md
> +마이크로 서비스 구조의 서버리스 프레임워크인 OpenFx에서 함수는 독립적으로 배포가 가능하며 개별적으로 실행될 수 있는 하나의 서비스로 정의된다. OpenFx에 배포되어 있는 서비스 내부에서 다른 서비스를 호출할 수 있으며, 이를 통해 사용자는 서로 다른 서비스를 엮어 원하는 기능의 애플리케이션 서비스를 완성할 수 있다.
여기 수정 안되었습니다.
수정 안하신 이유가 있을까요?

2020-09-04 08:20 UTC, ssaru commented on docs/source/3_getting_started/4_invoke_internal_service/index.md
> +Handler 코드 작성 후에, 다음 [링크](http://github.com/keti-openfx/openfx/docs/source/3_getting_started/2_deploying_functions/index.rst)의 #Build Function부터 순차적으로 진행하면 다른 서비스를 호출하는 함수가 OpenFx에 배포된다. 호출 시에는 사용자가
지금 활용하고 있는 문서화 도구는 파이썬 문서화 도구인 sphinx라는 도구입니다.

sphinx는 정적 사이트 생성기(Static Web Generator)로, 사용자가 작성한 *.rst, *.md와 같은 마키업 언어들을 html로 변환해주는 역활을 합니다.

이렇게 생성된 html파일을 웹 호스팅해서 문서화가 웹에 뜨는 것입니다.

*.rst파일을 링크로 엮었으니 링크가 안뜨는 겁니다.

2020-09-04 08:21 UTC, ssaru requested changes
@imxsuu 
코멘트 완료하였습니다.
해당 PR은 마지막 수정 후 반영하면 좋을 것 같습니다.

2020-09-04 08:32 UTC, imxsuu commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +​ └── handler.
알아보니, 영윤오빠도 `>` 문법을 사용했고, 그 부분에 대한 처리를 동현씨가 해주기로 하셨다고 들어서,, 저도 기존의 틀을 유지하도록 하겠습니다 ~

2020-09-04 09:01 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +``$ openfx-cli function init <FUNCTION NAME> -r <RUNTIME> [-f <YAML FILE NAME>.yaml] [-g <호스트 OS IP>:31113>]   >>    Folder: <FUNCTION NAME> created   Fucntion handler created in folder: <FUNCTION NA
코드블록(```)으로 하면 될 겁니다.

2020-09-04 09:01 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +    -  Java
이 부분은 변환하고 make html해서 렌더된 사이트 보면서 체크하고 수정할 수 밖에 없을 것 같네요.

2020-09-04 09:03 UTC, ssaru commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +​ └── handler.
일반적으로 파일 디렉토리를 표현하는 경우에는 인용(BlockQuote)이 아니라 코드블록(```)으로 사용하긴 합니다만
그냥 두셔도 됩니다.
그 부분은 제가 추후에 살펴보도록 할게요.

2020-09-07 05:36 UTC, imxsuu commented on docs/source/3_getting_started/2_deploying_functions/index.rst
> +​ └── handler.
우선 이 부분은 제가 여러가지 방법으로 시도를 해봤는데.. 계속 깨져서 일단은 그대로 두도록 하겠습니다...ㅜㅜ

2020-09-07 05:47 UTC, imxsuu commented on docs/source/3_getting_started/4_invoke_internal_service/index.md
> +마이크로 서비스 구조의 서버리스 프레임워크인 OpenFx에서 함수는 독립적으로 배포가 가능하며 개별적으로 실행될 수 있는 하나의 서비스로 정의된다. OpenFx에 배포되어 있는 서비스 내부에서 다른 서비스를 호출할 수 있으며, 이를 통해 사용자는 서로 다른 서비스를 엮어 원하는 기능의 애플리케이션 서비스를 완성할 수 있다.
수정했습니당

2020-09-07 05:49 UTC, imxsuu commented
> @imxsuu
> 코멘트 완료하였습니다.
> 해당 PR은 마지막 수정 후 반영하면 좋을 것 같습니다.

우선은 피드백에 대한 내용 모두 반영완료하였습니다.
디렉토리 트리를 표현하는 코드블록 이슈와 `>` 문법에 대한 이슈는 아직 미해결 상태입니다.

2020-09-10 02:29 UTC, ssaru approved these changes

2020-09-10 02:29 UTC, merged