메뉴얼 업데이트 1차
keti-openfx/openfx pull request #30
Opened 2020-09-03 06:18 UTC by HanHoRang

# Pull Request

keti-openfx/openfx 레파지토리에 기여해주셔서 감사드립니다.

해당 PR을 제출하기 전에 아래 사항이 완료되었는지 확인 부탁드립니다:

- [ ] 작성한 코드가 어떤 에러나 경고없이 빌드가 되었나요?
- [ ] 충분한 테스트를 수행하셨나요?

## 1. 해당 PR은 어떤 내용인가요?

#24 

예제 업데이트 중 

## 2. PR과 관련된 이슈가 있나요?

2020-09-03 08:56 UTC, HanHoRang commented
예제 업데이트 완료했습니다.

2020-09-03 10:01 UTC, ssaru commented on docs/conf.py
> +import sphinx_rtd_theme
이 파일은 이미 `docs/source/conf.py`에 있는데, 왜 다시 생성하셨나요?

2020-09-03 10:11 UTC, ssaru commented on docs/source/1_introduction/index.md
> +- CLI를 이용한 쉬운 함수 배포
약어는 풀이해서 써주세요.

```suggestion
- CLI(Command line interface)를 이용한 쉬운 함수 배포
```

2020-09-03 10:17 UTC, ssaru commented on docs/source/4_examples/index.rst
> +
table이 안나옵니다.

2020-09-03 10:18 UTC, ssaru commented on docs/source/4_examples/index.rst
> +    Directory: sentiment-analysis is created.
여기서부터 아래 페이지까지 전체 렌더링이 안됩니다.
make html해서 결과 나오는지 확인 부탁드립니다.

2020-09-03 10:20 UTC, ssaru commented on docs/source/4_examples/index.rst
> +링크 <https://github.com/keti-openfx/openfx-cli/blob/master/README.md>`__\ 에서
GitHub README 페이지로 안내하는 것이 아니라, 문서 내 OpenFx 설치와 CLI 설치란으로 리다이렉션 걸어주는게 좋아보입니다.

2020-09-03 10:24 UTC, ssaru commented on docs/source/4_examples/index.rst
> +사용하였다.
감정 분석 예제가 정확히 어떤 작업을 하는 예제인지
"감정 분석"이라는게 어떤 감정을 분석하고 입출력 데이터가 무엇이고에 대한 설명을 추가해주는게 좋을 것 같습니다.

[Object Detection Tutorial in TensorFlow: Real-Time Object Detection](https://www.edureka.co/blog/tensorflow-object-detection-tutorial/)를 참고하시면 좋아보입니다.

해당 링크처럼 What is Object Detection을 장황하게 설명할 필요는 없지만, 적어도 간략한 설명과 그림예시 같은 것이 있으면 좋을 것 같습니다.

2020-09-03 10:27 UTC, ssaru commented on docs/source/4_examples/index.rst
> +Image Processing
여기도 같습니다.
간략한 개요는 설명해주세요.

2020-09-03 10:28 UTC, ssaru commented on docs/source/4_examples/index.rst
> +    address = 'keti'
규모있는 코드를 작성하면 대략적으로 코드가 어떻게 작동하는지는 설명하는게 좋아보입니다.

2020-09-03 10:30 UTC, ssaru commented on docs/source/4_examples/index.rst
> +사이의 통신 프로토콜로 사용되고 있다. MQTT 프로토콜은 메시지를
```suggestion
MQTT(Message Queuing Telemetry Transport)는 TCP/IP 기반의 경량 Publish/Subscribe
메세징 프로토콜이다. 경량화 및 저전력 통신으로 인해 MQTT는 IOT 기기 사이의 통신 프로토콜로 사용되고 있다.  MQTT 프로토콜은 메시지를
```

2020-09-03 10:34 UTC, ssaru commented on docs/source/4_examples/index.rst
> +^^^^^^^^^^^^^^^^^^^
여기는 개요를 잘 적으셨네요

2020-09-03 10:36 UTC, ssaru commented on docs/source/4_examples/index.rst
> +같은 정적 언어인 경우 타입 변환에 신경을 써야한다.
이 내용은 불필요한 내용 같습니다.
```suggestion
```

2020-09-03 10:38 UTC, ssaru commented on docs/source/4_examples/index.rst
> +감정 분석을 위해
개요와 그림 부탁합니다.

2020-09-03 10:43 UTC, ssaru commented on docs/source/5_components/1_architecture/index.md
> +### Technical overview
컴포넌트 전체를 설명해주세요~
그림에 프로메테우스, OAuth, DataBase등이 있는데, 그 내용이 모두 빠졌습니다.
아니면 그림에서 프로메테우스, OAuth, DataBase를 빼는게 좋을 것 같구요.

컴포넌트란은 아키텍쳐 레벨이 어떻게 얽혀있는지 설명하기 위해서 만들어둔 목록입니다.
따라서 OpenFx를 구성하고 있는 모든 컴포넌트에 대해서 적어야합니다.

2020-09-03 10:45 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +늘고 있으며 오픈소스 기반의 서버리스 프레임워크에 대한 관련 연구가 진행
이 부분은 의미가 없는 내용입니다.

문서에는 1). 어떻게 사용하고, 2). 어떻게 구성되어있는지, 3). 구성 요소를 선택하고 지원한 이유는 무엇인지(장/단점)만 적어주면 될 것 같습니다.

2020-09-03 10:45 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +데이터 노출의 취약점이 발생한ㄷ,
오탈자
```suggestion
데이터 노출의 취약점이 발생한다
```

2020-09-03 10:48 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +데이터 노출의 취약점이 발생한ㄷ,
이 내용도 의미가 없습니다.
메뉴얼 목적에 맞게 정보를 제공하는게 좋을 것 같습니다.

제가 생각했을 때는, 이 문서를 읽는 사람들은 OpenFx를 사용하고 어떻게 구성되어있는지 확인하기위해서 들어온 사람들이지, OAuth나 인증 시스템을 공부하려고 들어온 사람들은 아닌 것 같습니다.

2020-09-03 10:51 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +그 결과 OAuth2를 통해 클라이언트 단위별 네임스페이스 리소스를 제공하여
"클라이언트 단위"라는게 무엇을 의미하는지 모르겠습니다.

클라인트는 서버-클라이언트에서의 클라이언트를 의미하는데, 여기서 클라이언트 "단위"라고 하는 단어는 무엇을 의미하나요?

2020-09-03 10:52 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +그 결과 OAuth2를 통해 클라이언트 단위별 네임스페이스 리소스를 제공하여
그냥 "접근 권한별"과 같은 일반적인 단어로 대체하는 게 나을 것 같습니다.

2020-09-03 10:55 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +권한별 API 권한 설정을 위해 코어 개발을 완료했다. API 실행 권한은 OAuth2
"OpenFx에서의 보안 기술로 OAuth2 적용을 통한 접근 인가와 더불어 사용자 권한별 API 권한 설정을 위해 코어 개발을 완료했다."

이런 내용은 의미가 없습니다...
사용자는 우리가 무엇가 어떤 대단한 것을 개발했는지 알기 위해서 문서를 보는 것이 아닙니다.

그리고 OAuth는 보안기술이 아닙니다. 잘못된 용어의 사용은 큰 문제를 발생시킬 수 있습니다.

2020-09-03 10:59 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +Auth가 적용된 OpenFx의 API를 호출하기 위해서는 OAuth2가 발급하는
OAuth인가요 Auth인가요?
용어 통일 부탁드립니다.

2020-09-03 10:59 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +
개행이 너무 많습니다.

2020-09-03 11:00 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +^^^^^^^^^^^^^^
타이틀을 영어로 작성하실거면 영어로 쓰시고, 한글로 쓰실거면 한글로만 써주세요.

2020-09-03 11:02 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +OAuth2 클라이언트 정보같은 경우, OpenFx 관리자(tmdgh7186@keti.re.kr)에게
OpenFx 관리자(tmdgh7186@keti.re.kr) -> 개인정보는 빼주시기 바랍니다.

2020-09-03 11:03 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +클라이언트 정보이다.
해당 문서의 대상은 온프레미스나 클라우드 환경에 OpenFx를 설치하는 사용자를 대상으로 한 문서입니다.
이런 내용은 의미가 없습니다.

2020-09-03 11:04 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +^^^^^^^^^^^^^^
이 내용은 컴포넌트란에 오면 안됩니다.
Example이나 Getting Started로 옮겨주세요.

2020-09-03 11:06 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +    Client ID : alqzkxu4Bw.keti-openfx
OpenFx에 적용된 OAuth에 대한 소개는 위에서 했으니,

How to use부터 맨 마지막까지의 내용은, 자신의 온프레미스 혹은 클라우드에 OpenFx를 설치하는 사용자를 대상으로 
OpenFx를 자신의 클러스터 환경에 설치했을 때, 어떻게 OAuth 부분을 커스텀할 수 있는지에 대한 내용으로 재작성 부탁드립니다.

실 구현에 가깝게 어떤형태로 구성되어있는지요.

2020-09-03 11:07 UTC, ssaru commented on docs/source/7_references/4_auth_reference/index.rst
> +경우, OpenFx 관리자에게 별도의 메일(tmdgh7186@keti.re.kr)로 신청하여
개인정보 빼주세요.

2020-09-03 11:08 UTC, ssaru commented on docs/source/7_references/4_auth_reference/index.rst
> +호환호환하지않는다. http에서 제공하는 표준안의 차선책(개인 정보는
오탈자 및 구문 흐름이 이상합니다.

2020-09-03 11:13 UTC, ssaru commented on docs/source/6_roadmap/index.md
> + ![roadmap](./roadmap.png)
과거부터 지금까지의 개발방향을 보고싶어서 로드맵을 추가하란게 아니구요.
지금까지 개발한 기능 리스트를 쭉 나열하고 앞으로 어떤 기능을 개발할 것이를 명시적으로 리스트 업해서 
그림 그려서 올려주세요.....

2020-09-03 11:15 UTC, ssaru commented on docs/source/7_references/5_benchmark/index.md
> +Y축 좌표인 Average Response Time(ms) 은 평균 응답 시간으로 적을 수록 빠른 응답성 보여주는 지표이다.  실험 결과에 따르면 OpenFx의 평균 응답시간은 동시접속이 100이상부터 타 서버리스 플랫폼과 비교 성능적으로 큰 차이로 적어지는 것을 알 수 있었다.
이런 문장을 작성하시려면 도표에 대한 내용을 모두 서술해주시기 바랍니다.
X축은 뭔지 Y축은 뭔지, 등등

2020-09-03 11:16 UTC, ssaru requested changes
@HanHoRang 
코멘트 달았습니다.
수정하실 때 메뉴얼 작성 목적과, 사용자가 이를 읽었을 때, 해당 내용이 쉽게 읽히는지에 대한 고려를 부탁드립니다.

2020-09-05 13:20 UTC, HanHoRang commented
피드백 반영 내역
-------
오탈자 및 문맥 오류 수정했습니다.


+ 원격 접속을 하지못해 반영못한 피드백은 7일날까지 완료하겠습니다.
-------
로드맵
Oauth2 커스텀 관련 문서

2020-09-06 17:04 UTC, ssaru commented
@HanHoRang 
알겠습니다.
피드백 반영한 내용은 `Resolve conversation` 체크 부탁드립니다.

2020-09-08 02:10 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +데이터 노출의 취약점이 발생한ㄷ,
삭제했습니다.

2020-09-08 02:14 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +그 결과 OAuth2를 통해 클라이언트 단위별 네임스페이스 리소스를 제공하여
내용 지웠습니답 

+) 클라이언트는 OAuth2 의 용어로 서드 어플리케이션을 뜻합니다. 클라이언트 단위는 서드 어플리케이션 단위를 말하는 것이며 어플리케이션별 네임스페이스 리소스를 제공한다는 의미로 작성하였습니다

2020-09-08 02:18 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +그 결과 OAuth2를 통해 클라이언트 단위별 네임스페이스 리소스를 제공하여
내용 삭제했습니다

2020-09-08 02:26 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +권한별 API 권한 설정을 위해 코어 개발을 완료했다. API 실행 권한은 OAuth2
내용은 삭제했습니다

+) OAuth2는 인가 프로토콜로 기술 목적은 인가 기술에 있습니다 (https://ko.wikipedia.org/wiki/OAuth)
인증, 인가는 결국 컴퓨터 보안에 사용되는 기술로 보안 기술로 표현했는데 용어 사용에 신중하겠습니다

2020-09-08 02:26 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +OAuth2 클라이언트 정보같은 경우, OpenFx 관리자(tmdgh7186@keti.re.kr)에게
넵

2020-09-08 02:30 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +^^^^^^^^^^^^^^
한글로 통일하겠습니다

2020-09-08 02:34 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +클라이언트 정보이다.
반영했습니다, 내용 지웠어요

2020-09-08 04:03 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +Auth가 적용된 OpenFx의 API를 호출하기 위해서는 OAuth2가 발급하는
축약어 입니답..
OAuth2  - OAuth2  기술..
Auth 인증 기술 전반을 칭함

2020-09-08 04:03 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +Auth가 적용된 OpenFx의 API를 호출하기 위해서는 OAuth2가 발급하는
용어 수정했습니다.

2020-09-08 05:43 UTC, HanHoRang commented on docs/conf.py
> +import sphinx_rtd_theme
마크다운 문서의 테이블을 스핑크스에서 호환시키고자 conf.py를 수정했습니다. 아마 빌드하는 과정에서 생성했나봅니다
그러나 일부분 테이블 호환이 안되는 것을 확인하였고 .rst 변환을 통해 해결했습니다. 

결국 필요없는 문서로 삭제했습니다~

2020-09-08 05:43 UTC, HanHoRang commented on docs/source/4_examples/index.rst
> +Image Processing
개요 및 그림 추가 완료

2020-09-08 05:43 UTC, HanHoRang commented on docs/source/4_examples/index.rst
> +    address = 'keti'
클래스, 함수 설명 추가했습니다.

2020-09-08 08:11 UTC, HanHoRang commented on docs/source/6_roadmap/index.md
> + ![roadmap](./roadmap.png)
20년도 로드맵 작성해서 올렸습니다.

2020-09-08 08:15 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +^^^^^^^^^^^^^^
example로 옮겼습니다.

2020-09-08 08:29 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +    Client ID : alqzkxu4Bw.keti-openfx
`어떻게 OAuth2 부분을 커스텀할 수 있는지에 대한 내용` 에서 커스텀이 무엇을 말하는 것인가요? 

사용자가 접근 토큰을 수정해서 제공하는 허용 리소스를 변경하거나 권한 DB를 구축해서 접근 권한에 따른 허용 API를 조절하는 것을 뜻하는건가요? 


음..  커스텀은 메뉴얼 작성 범위에 초과되는 내용인 것 같습니다
해당 문서는 저희가 설계한 접근 인가 기술에 대해서의 메뉴얼 작성이지 커스텀까지라고 하시면 코드 핸드링까지 전부 알려줘야해서 내용이 방대할 뿐더러 배경 지식이 많이 필요합니다. 

차라리 OpenFx를 설치하는 사용자를 위한 메뉴얼이라고 하신다면 가상 시나리오를 구성해서 클라이언트단위별 네임스페이스 발급 방법, 사용자 회원가입 방법,  간단한 API 호출로 구성해서 작성할까요?

2020-09-08 08:36 UTC, HanHoRang commented on docs/source/5_components/4_auth/index.rst
> +^^^^^^^^^^^^^^
동민형이 말해주시기를 OAuth2가 적용된 OpenFx와 적용안된 OpenFx 로 나눠 운영하자 하셨습니다.
이에 따라 메뉴얼도 두 가지 버전으로 작성해달라 요청하셨습니다.

제 생각에는 사용자가 메뉴얼을 읽고 그대로 따라하기엔 버전이 달라 혼돈이 생길 우려가 생기는데 
OAuth2 관련 메뉴얼을 모아서 작성하는 것이 어떨까요?

2020-09-10 02:33 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +^^^^^^^^^^^^^^
그러면 OAuth2 개발당시에 이를 플러그인 방식으로 개발하여, 몇가지 파라미터 셋팅을 하면, enable/disable할 수 있는 구조로 만든 다음에 문서에 OAuth란에 플러그인 방식으로 되어있어 쉽게 붙였다 뗄수 있다라고 소개하면 될 듯합니다.

2020-09-10 02:36 UTC, ssaru commented on docs/source/5_components/4_auth/index.rst
> +    Client ID : alqzkxu4Bw.keti-openfx
라이브러리, SDK 혹은 소스코드를 다루는 프레임워크가 아니기 때문에, 코드 레벨의 핸들링은 나올 필요가 없습니다.
네임스페이스 컨트롤, 사용자 회원가입에 대한 몇 가지 변경가능한 파라미터 셋팅들이 모두 하드코딩 되어있나보군요.

이 부분은 그냥 패스하시죠.

2020-09-10 02:36 UTC, ssaru approved these changes

2020-09-10 02:36 UTC, merged